version: "3"

services:
  node:
    container_name: ${CI_PROJECT_NAME}_node
    build:
      context: ../../
      dockerfile: config/docker/dockerfiles/node/Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ../../:/usr/src
    command: 
      bash -c "node --inspect-brk=0.0.0.0 ."      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`quotes.nollim`)"  

  mysql:
    image: mariadb:latest
    container_name: ${CI_PROJECT_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${CI_PROJECT_NAME}
      MYSQL_DATABASE: ${CI_PROJECT_NAME}
      MYSQL_USER: ${CI_PROJECT_NAME}
      MYSQL_PASSWORD: ${CI_PROJECT_NAME}
    restart: always
    labels:
      - "traefik.enable=false"

  traefik:
    container_name: ${CI_PROJECT_NAME}_traefik
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"    
